name: Fixing Bugs Auto

on:
  schedule:
    - cron: '0 8 * * *' # every day at 8 AM UTC
  workflow_dispatch:     # allow manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Git user
        run: |
          git config --global user.name "sameer.panda"
          git config --global user.email "sameerpandausa@gmail.com"

      - name: Fixing Crucial Bugs
        run: |
          DAY_NUM=$(date -u +%u)
          echo "Today is day number: $DAY_NUM"
          for i in $(seq 1 $DAY_NUM); do
            echo "Green tick $i on $(date -u)" >> activity.log
            git add activity.log
            git commit -m "chore: Fixing Crucial Bug #$i" || echo "Nothing to commit"
            git push
          done
